// Code generated by gen-error-code. DO NOT EDIT.
// Version: 1.0.0
// Description: Prism 项目错误码注册表
// Generated at: 2025-10-01 21:23:03

package prism

// 错误码定义
// 所有错误码都在 error_code.json 中注册
//
// 分类说明:
//   common: 通用错误和基础错误类型 (0, 1000-1999)
//   auth: 认证和授权相关错误 (2000-2999)
//   resource: 资源相关错误（订阅、节点、路由等） (3000-3999)
//   validation: 输入验证相关错误 (4000-4999)
//   service: 服务错误（数据库、缓存等） (5000-5999)
//   queue: 消息队列相关错误 (6000-6999)
//   config: 配置文件和设置错误 (7000-7999)
//   network: 网络、代理、DNS 等错误 (8000-8999)
const (
	// ErrCommonSuccess 操作成功 (0)
	ErrCommonSuccess int32 = 0
	// ErrCommonInternalError 内部错误 (1000)
	ErrCommonInternalError int32 = 1000
	// ErrCommonInvalidRequest 无效的请求 (1001)
	ErrCommonInvalidRequest int32 = 1001
	// ErrCommonNotFound 资源未找到 (1002)
	ErrCommonNotFound int32 = 1002
	// ErrCommonAlreadyExists 资源已存在 (1003)
	ErrCommonAlreadyExists int32 = 1003
	// ErrCommonTimeout 操作超时 (1004)
	ErrCommonTimeout int32 = 1004
	// ErrCommonTooManyRequests 请求过多 (1005)
	ErrCommonTooManyRequests int32 = 1005
	// ErrCommonServiceUnavailable 服务不可用 (1006)
	ErrCommonServiceUnavailable int32 = 1006
	// ErrCommonMethodNotAllowed 方法不允许 (1007)
	ErrCommonMethodNotAllowed int32 = 1007
	// ErrCommonUnprocessableEntity 无法处理的实体 (1008)
	ErrCommonUnprocessableEntity int32 = 1008
	// ErrAuthUnauthorized 未授权 (2000)
	ErrAuthUnauthorized int32 = 2000
	// ErrAuthForbidden 禁止访问 (2001)
	ErrAuthForbidden int32 = 2001
	// ErrAuthInvalidToken 无效的令牌 (2002)
	ErrAuthInvalidToken int32 = 2002
	// ErrAuthTokenExpired 令牌已过期 (2003)
	ErrAuthTokenExpired int32 = 2003
	// ErrAuthInvalidCredentials 无效的凭证 (2004)
	ErrAuthInvalidCredentials int32 = 2004
	// ErrSubscriptionNotFound 订阅不存在 (3000)
	ErrSubscriptionNotFound int32 = 3000
	// ErrSubscriptionAlreadyExists 订阅已存在 (3001)
	ErrSubscriptionAlreadyExists int32 = 3001
	// ErrSubscriptionInvalid 订阅无效 (3002)
	ErrSubscriptionInvalid int32 = 3002
	// ErrSubscriptionUpdateFailed 订阅更新失败 (3003)
	ErrSubscriptionUpdateFailed int32 = 3003
	// ErrNodeNotFound 节点不存在 (3100)
	ErrNodeNotFound int32 = 3100
	// ErrNodeTestFailed 节点测试失败 (3101)
	ErrNodeTestFailed int32 = 3101
	// ErrNodeUnavailable 节点不可用 (3102)
	ErrNodeUnavailable int32 = 3102
	// ErrRouteNotFound 路由规则不存在 (3200)
	ErrRouteNotFound int32 = 3200
	// ErrRouteInvalid 路由规则无效 (3201)
	ErrRouteInvalid int32 = 3201
	// ErrGeoipInvalidIp 无效的 IP 地址 (3300)
	ErrGeoipInvalidIp int32 = 3300
	// ErrGeoipDatabaseOpenFailed 打开 GeoIP 数据库失败 (3301)
	ErrGeoipDatabaseOpenFailed int32 = 3301
	// ErrGeoipDatabaseWriteFailed 写入 GeoIP 数据库失败 (3302)
	ErrGeoipDatabaseWriteFailed int32 = 3302
	// ErrGeoipConversionFailed GeoIP 数据转换失败 (3303)
	ErrGeoipConversionFailed int32 = 3303
	// ErrGeoipFileOperationFailed GeoIP 文件操作失败 (3304)
	ErrGeoipFileOperationFailed int32 = 3304
	// ErrGeoipWriterCreateFailed 创建 GeoIP 写入器失败 (3305)
	ErrGeoipWriterCreateFailed int32 = 3305
	// ErrGeoipInsertFailed 插入 GeoIP 数据失败 (3306)
	ErrGeoipInsertFailed int32 = 3306
	// ErrValidationFailed 验证失败 (4000)
	ErrValidationFailed int32 = 4000
	// ErrValidationUrlRequired URL 不能为空 (4001)
	ErrValidationUrlRequired int32 = 4001
	// ErrValidationUrlInvalid URL 格式无效 (4002)
	ErrValidationUrlInvalid int32 = 4002
	// ErrValidationTitleRequired 标题不能为空 (4003)
	ErrValidationTitleRequired int32 = 4003
	// ErrValidationPortInvalid 端口号无效 (4004)
	ErrValidationPortInvalid int32 = 4004
	// ErrValidationEmailInvalid 邮箱格式无效 (4005)
	ErrValidationEmailInvalid int32 = 4005
	// ErrValidationFieldRequired 字段不能为空 (4006)
	ErrValidationFieldRequired int32 = 4006
	// ErrValidationFieldTooLong 字段过长 (4007)
	ErrValidationFieldTooLong int32 = 4007
	// ErrValidationFieldTooShort 字段过短 (4008)
	ErrValidationFieldTooShort int32 = 4008
	// ErrServiceDatabaseError 数据库错误 (5000)
	ErrServiceDatabaseError int32 = 5000
	// ErrServiceCacheError 缓存错误 (5001)
	ErrServiceCacheError int32 = 5001
	// ErrServiceConnectionFailed 连接失败 (5002)
	ErrServiceConnectionFailed int32 = 5002
	// ErrQueueFull 队列已满 (6000)
	ErrQueueFull int32 = 6000
	// ErrQueueEmpty 队列为空 (6001)
	ErrQueueEmpty int32 = 6001
	// ErrQueueClosed 队列已关闭 (6002)
	ErrQueueClosed int32 = 6002
	// ErrQueueTimeout 队列操作超时 (6003)
	ErrQueueTimeout int32 = 6003
	// ErrQueueInvalidConcurrency 无效的并发数 (6004)
	ErrQueueInvalidConcurrency int32 = 6004
	// ErrQueueUnsupportedType 不支持的队列类型 (6005)
	ErrQueueUnsupportedType int32 = 6005
	// ErrQueueMaxRetriesExceeded 超过最大重试次数 (6006)
	ErrQueueMaxRetriesExceeded int32 = 6006
	// ErrConfigInvalid 配置无效 (7000)
	ErrConfigInvalid int32 = 7000
	// ErrConfigNotFound 配置未找到 (7001)
	ErrConfigNotFound int32 = 7001
	// ErrConfigParseFailed 配置解析失败 (7002)
	ErrConfigParseFailed int32 = 7002
	// ErrProxyConnectionFailed 代理连接失败 (8000)
	ErrProxyConnectionFailed int32 = 8000
	// ErrProxyTimeout 代理超时 (8001)
	ErrProxyTimeout int32 = 8001
	// ErrProxyAuthFailed 代理认证失败 (8002)
	ErrProxyAuthFailed int32 = 8002
	// ErrNetworkUnreachable 网络不可达 (8100)
	ErrNetworkUnreachable int32 = 8100
	// ErrNetworkDnsResolveFailed DNS 解析失败 (8101)
	ErrNetworkDnsResolveFailed int32 = 8101
)

// ErrorCodeInfo 错误码信息
type ErrorCodeInfo struct {
	Code        int32
	Key         string
	Category    string
	Description string
}

// errorCodeMap 错误码映射表
var errorCodeMap = map[int32]ErrorCodeInfo{
	0: {
		Code:        0,
		Key:         "common.success",
		Category:    "common",
		Description: "操作成功",
	},
	1000: {
		Code:        1000,
		Key:         "common.internal_error",
		Category:    "common",
		Description: "内部错误",
	},
	1001: {
		Code:        1001,
		Key:         "common.invalid_request",
		Category:    "common",
		Description: "无效的请求",
	},
	1002: {
		Code:        1002,
		Key:         "common.not_found",
		Category:    "common",
		Description: "资源未找到",
	},
	1003: {
		Code:        1003,
		Key:         "common.already_exists",
		Category:    "common",
		Description: "资源已存在",
	},
	1004: {
		Code:        1004,
		Key:         "common.timeout",
		Category:    "common",
		Description: "操作超时",
	},
	1005: {
		Code:        1005,
		Key:         "common.too_many_requests",
		Category:    "common",
		Description: "请求过多",
	},
	1006: {
		Code:        1006,
		Key:         "common.service_unavailable",
		Category:    "common",
		Description: "服务不可用",
	},
	1007: {
		Code:        1007,
		Key:         "common.method_not_allowed",
		Category:    "common",
		Description: "方法不允许",
	},
	1008: {
		Code:        1008,
		Key:         "common.unprocessable_entity",
		Category:    "common",
		Description: "无法处理的实体",
	},
	2000: {
		Code:        2000,
		Key:         "auth.unauthorized",
		Category:    "auth",
		Description: "未授权",
	},
	2001: {
		Code:        2001,
		Key:         "auth.forbidden",
		Category:    "auth",
		Description: "禁止访问",
	},
	2002: {
		Code:        2002,
		Key:         "auth.invalid_token",
		Category:    "auth",
		Description: "无效的令牌",
	},
	2003: {
		Code:        2003,
		Key:         "auth.token_expired",
		Category:    "auth",
		Description: "令牌已过期",
	},
	2004: {
		Code:        2004,
		Key:         "auth.invalid_credentials",
		Category:    "auth",
		Description: "无效的凭证",
	},
	3000: {
		Code:        3000,
		Key:         "subscription.not_found",
		Category:    "resource",
		Description: "订阅不存在",
	},
	3001: {
		Code:        3001,
		Key:         "subscription.already_exists",
		Category:    "resource",
		Description: "订阅已存在",
	},
	3002: {
		Code:        3002,
		Key:         "subscription.invalid",
		Category:    "resource",
		Description: "订阅无效",
	},
	3003: {
		Code:        3003,
		Key:         "subscription.update_failed",
		Category:    "resource",
		Description: "订阅更新失败",
	},
	3100: {
		Code:        3100,
		Key:         "node.not_found",
		Category:    "resource",
		Description: "节点不存在",
	},
	3101: {
		Code:        3101,
		Key:         "node.test_failed",
		Category:    "resource",
		Description: "节点测试失败",
	},
	3102: {
		Code:        3102,
		Key:         "node.unavailable",
		Category:    "resource",
		Description: "节点不可用",
	},
	3200: {
		Code:        3200,
		Key:         "route.not_found",
		Category:    "resource",
		Description: "路由规则不存在",
	},
	3201: {
		Code:        3201,
		Key:         "route.invalid",
		Category:    "resource",
		Description: "路由规则无效",
	},
	3300: {
		Code:        3300,
		Key:         "geoip.invalid_ip",
		Category:    "resource",
		Description: "无效的 IP 地址",
	},
	3301: {
		Code:        3301,
		Key:         "geoip.database_open_failed",
		Category:    "resource",
		Description: "打开 GeoIP 数据库失败",
	},
	3302: {
		Code:        3302,
		Key:         "geoip.database_write_failed",
		Category:    "resource",
		Description: "写入 GeoIP 数据库失败",
	},
	3303: {
		Code:        3303,
		Key:         "geoip.conversion_failed",
		Category:    "resource",
		Description: "GeoIP 数据转换失败",
	},
	3304: {
		Code:        3304,
		Key:         "geoip.file_operation_failed",
		Category:    "resource",
		Description: "GeoIP 文件操作失败",
	},
	3305: {
		Code:        3305,
		Key:         "geoip.writer_create_failed",
		Category:    "resource",
		Description: "创建 GeoIP 写入器失败",
	},
	3306: {
		Code:        3306,
		Key:         "geoip.insert_failed",
		Category:    "resource",
		Description: "插入 GeoIP 数据失败",
	},
	4000: {
		Code:        4000,
		Key:         "validation.failed",
		Category:    "validation",
		Description: "验证失败",
	},
	4001: {
		Code:        4001,
		Key:         "validation.url_required",
		Category:    "validation",
		Description: "URL 不能为空",
	},
	4002: {
		Code:        4002,
		Key:         "validation.url_invalid",
		Category:    "validation",
		Description: "URL 格式无效",
	},
	4003: {
		Code:        4003,
		Key:         "validation.title_required",
		Category:    "validation",
		Description: "标题不能为空",
	},
	4004: {
		Code:        4004,
		Key:         "validation.port_invalid",
		Category:    "validation",
		Description: "端口号无效",
	},
	4005: {
		Code:        4005,
		Key:         "validation.email_invalid",
		Category:    "validation",
		Description: "邮箱格式无效",
	},
	4006: {
		Code:        4006,
		Key:         "validation.field_required",
		Category:    "validation",
		Description: "字段不能为空",
	},
	4007: {
		Code:        4007,
		Key:         "validation.field_too_long",
		Category:    "validation",
		Description: "字段过长",
	},
	4008: {
		Code:        4008,
		Key:         "validation.field_too_short",
		Category:    "validation",
		Description: "字段过短",
	},
	5000: {
		Code:        5000,
		Key:         "service.database_error",
		Category:    "service",
		Description: "数据库错误",
	},
	5001: {
		Code:        5001,
		Key:         "service.cache_error",
		Category:    "service",
		Description: "缓存错误",
	},
	5002: {
		Code:        5002,
		Key:         "service.connection_failed",
		Category:    "service",
		Description: "连接失败",
	},
	6000: {
		Code:        6000,
		Key:         "queue.full",
		Category:    "queue",
		Description: "队列已满",
	},
	6001: {
		Code:        6001,
		Key:         "queue.empty",
		Category:    "queue",
		Description: "队列为空",
	},
	6002: {
		Code:        6002,
		Key:         "queue.closed",
		Category:    "queue",
		Description: "队列已关闭",
	},
	6003: {
		Code:        6003,
		Key:         "queue.timeout",
		Category:    "queue",
		Description: "队列操作超时",
	},
	6004: {
		Code:        6004,
		Key:         "queue.invalid_concurrency",
		Category:    "queue",
		Description: "无效的并发数",
	},
	6005: {
		Code:        6005,
		Key:         "queue.unsupported_type",
		Category:    "queue",
		Description: "不支持的队列类型",
	},
	6006: {
		Code:        6006,
		Key:         "queue.max_retries_exceeded",
		Category:    "queue",
		Description: "超过最大重试次数",
	},
	7000: {
		Code:        7000,
		Key:         "config.invalid",
		Category:    "config",
		Description: "配置无效",
	},
	7001: {
		Code:        7001,
		Key:         "config.not_found",
		Category:    "config",
		Description: "配置未找到",
	},
	7002: {
		Code:        7002,
		Key:         "config.parse_failed",
		Category:    "config",
		Description: "配置解析失败",
	},
	8000: {
		Code:        8000,
		Key:         "proxy.connection_failed",
		Category:    "network",
		Description: "代理连接失败",
	},
	8001: {
		Code:        8001,
		Key:         "proxy.timeout",
		Category:    "network",
		Description: "代理超时",
	},
	8002: {
		Code:        8002,
		Key:         "proxy.auth_failed",
		Category:    "network",
		Description: "代理认证失败",
	},
	8100: {
		Code:        8100,
		Key:         "network.unreachable",
		Category:    "network",
		Description: "网络不可达",
	},
	8101: {
		Code:        8101,
		Key:         "network.dns_resolve_failed",
		Category:    "network",
		Description: "DNS 解析失败",
	},
}

// GetErrorCodeInfo 获取错误码信息
func GetErrorCodeInfo(code int32) (ErrorCodeInfo, bool) {
	info, ok := errorCodeMap[code]
	return info, ok
}

// IsValidErrorCode 检查错误码是否有效
func IsValidErrorCode(code int32) bool {
	_, ok := errorCodeMap[code]
	return ok
}
