# Prism Core - golangci-lint 配置文件

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
    - load

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/prism/core
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

  # 不要启用这些检查器
  disable:
    - maligned
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - errcheck
        - dupl
        - gosec

    - path: internal/testutil/
      linters:
        - gomnd
        - funlen

    - path: cmd/
      linters:
        - gomnd

    # 排除一些常见但不重要的问题
    - text: "Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked"
      linters:
        - errcheck

    - text: "func name will be used as test\.Test.* by other packages, and that stutters; consider calling this"
      linters:
        - golint

    - text: "G404: Use of weak random number generator"
      linters:
        - gosec
        
    - text: "G204: Subprocess launched with function call as argument or cmd arguments"
      linters:
        - gosec

  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: error
  case-sensitive: true
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gocritic
      severity: warning